import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


const sleep = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms));
// Skeleton loading 
function ListItemLoading() {
  return (
    <div className="grid h-[64px] items-center">
      <div className="w-full animate-pulse" role="status">
        <div className="h-2.5 w-full rounded-full bg-gray-200 dark:bg-gray-700" />
        <span className="sr-only">Loading...</span>
      </div>
      <div className="flex items-center justify-between">
        <div className="w-full animate-pulse" role="status">
          <div className="h-2.5 w-12 rounded-full bg-gray-200 dark:bg-gray-700" />
          <span className="sr-only">Loading...</span>
        </div>
        <div className="w-full animate-pulse" role="status">
          <div className="h-2.5 w-full rounded-full bg-gray-200 dark:bg-gray-700" />
          <span className="sr-only">Loading...</span>
        </div>
      </div>
    </div>
  );
}


async function LisItem({ id }: { id: number }) {
  await sleep(Math.random() * 3000);
  const post = await fetch(
    `https://hacker-news.firebaseio.com/v0/item/${id}.json?print=pretty`
  ).then(
    (res) => res.json() as Promise<{ text: string; title: string; by: string }>
  );

  return (
    <div className="flex h-[64px] flex-col gap-2">
      <p className="truncate">{post.title || post.text}</p>
      <div className="flex items-center justify-between opacity-50">
        <p>{post.by}</p>
        <p>Visit webvite {`>>`}</p>
      </div>
    </div>
  );
}

export default async function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  const post = await fetch(
    `https://hacker-news.firebaseio.com/v0/topstories.json?print=pretty&limitToFirst=10&orderBy="$key"`
  ).then((res) => res.json() as Promise<number[]>);
  return (
    <html lang="en">
      <body className="grid h-screen grid-rows-[60px, 1fr] bg-gray-100">
        {/* Cabecera */}
        <header className="grid place-content-center bg-yellow-400 font-semibold text-black">
          Uizard Reader
        </header>

        {/* Contenido principal con aside a la izquierda */}
        <main className="grid grid-cols-[320px,1fr] gap-4">
          <aside className="bg-black p-4 shadow-md h-full">
            <ul>
              {post.map((id) => (
                <Link key={id} href={`${id}`} >
                  <Suspense fallback={<ListItemLoading />}>
                <LisItem key={id} id={id}  />
                  </Suspense>
                </Link>
              ))}
            </ul>
          </aside>
          {/* Contenido principal derecha */}
          <section className="p-4 bg-black shadow-md">{children}</section>
        </main>
      </body>
    </html>
  );
}
